package com.hibernatehbm.spring;

/**
 * AccountsId generated by hbm2java
 */
public class Account  {

	private Integer accountNumber;
	private String owner;
	private Double balance;

	public Account() {
	}

	public Account(Integer accountNumber, String owner, Double balance) {
		this.accountNumber = accountNumber;
		this.owner = owner;
		this.balance = balance;
	}

	public Integer getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(Integer accountNumber) {
		this.accountNumber = accountNumber;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public Double getBalance() {
		return this.balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}

	 
}
